
CREATE TABLE KLIENCI 
(
  KLIENTID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL PRIMARY KEY 
, NAZWISKO VARCHAR(20) NOT NULL 
, IMIE VARCHAR(20) NOT NULL 
, PESEL CHAR(11) NULL UNIQUE
, DATA_UR DATE NULL
, DATA_ZATR DATE DEFAULT CURRENT_DATE 
, PENSJA DOUBLE PRECISION DEFAULT 0 NOT NULL 
, PENSJA_ROCZNA DOUBLE PRECISION PENSJA*12
, ULICA VARCHAR() NULL 
, NUMER VARCHAR() NULL
, MIESZKANIA INTEGER NULLCREATE
, MIASTOID INT 
);

CREATE TABLE MIASTA 
(
  MIASTOID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL PRIMARY KEY 
, NAZWA VARCHAR2(30 BYTE) NOT NULL 
, WOJEWODZTWOID INT
) ;

CREATE TABLE WOJEWODZTWA 
(
  WOJEWODZTWOID INT GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 START WITH 1 NOT NULL PRIMARY KEY 
, NAZWA VARCHAR2(30 BYTE) NOT NULL 
, AKTYWNE VARCHAR2(2 BYTE) DEFAULT 1 
) 
DROP TABLE WOJEWODZTWA